Polynomial Multiproof RPC
availproject/avail pull request #141
Opened 2023-03-17 05:25 UTC by Aphoh

This PR pulls in a big refactor in `avail-core`, and makes some big changes in the RPC implementation:
1. Switches from `Mutex<LRU>` to an asynchronous, performant cache backing grid generation in the api, which [coalesces requests for the same grid](https://docs.rs/moka/latest/moka/sync/struct.Cache.html#concurrent-calls-on-the-same-key-2). This means the DA grid is only constructed once, even with many parallel requests inbound.
2. Caches the ifft-d rows of the grid used in proof generation.
3. Allows easily for the caching proofs, but not currently implemented 😄 

Additionally, it adds one new rpc endpoint, `kate_queryMultiProof` which spits out multiproofs.

2023-04-18 07:07 UTC, Aphoh commented
Added multiproof retrieval and verification to the data submission example [here](https://github.com/availproject/avail/blob/149aaf1989d84a8a0ac42a69e4d903e7bd5b958b/avail-subxt/examples/submit_data.rs#L135)
@kroos47 Let me know if you see any blockers/anything you'd like for getting this worked into the light client.

2023-06-01 07:38 UTC, fmiguelgarcia requested changes

2023-06-01 07:38 UTC, fmiguelgarcia commented on Cargo.toml
> +da-primitives = { version = "0.4", git="https://github.com/maticnetwork/avail-core",  rev = "5bd30863f15cca7b0158319979202650dc775d04" }
We need to fix this deps.
We have to use `availproject` and specific `tag` instead of `rev`

2023-06-01 09:57 UTC, fmiguelgarcia requested changes

2023-06-01 09:57 UTC, fmiguelgarcia commented on pallets/system/Cargo.toml
> +  "kate/parallel",
nit: spaces/tabs

2023-06-01 09:57 UTC, fmiguelgarcia commented on pallets/system/src/header_builder.rs
> +	let grid = kate::gridgen::EvaluationGrid::from_extrinsics(
@Aphoh We need to merge your changes in `avail-core`, tag them and finally use here as dep.

2023-09-08 10:37 UTC, markopoloparadox commented
@Aphoh Should we rebase this branch? Is this PR tied to the to other PR that you have created https://github.com/availproject/avail/pull/196 ? :)

2023-10-07 03:10 UTC, Aphoh commented
Closing in favor of #254

2023-10-07 03:10 UTC, closed without merging